/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Guillaume.Rigaux
 * Created: 18-mai-2018
 */


--------------------------------------------------------
--  Fichier créé - jeudi-mai-17-2018   
--------------------------------------------------------


--------------------------------------------------------
--  DDL for Table ATTRIBUTION
--------------------------------------------------------

  CREATE TABLE "ATTRIBUTION" 
   (	"MATRICULE" VARCHAR2(4 BYTE), 
	"SIGLE" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Table CLASSE
--------------------------------------------------------

  CREATE TABLE "CLASSE" 
   (	"SIGLE" VARCHAR2(4 BYTE), 
	"ANNEE" NUMBER(1,0), 
	"ORIENTATION" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Table ENSEIGNANT
--------------------------------------------------------

  CREATE TABLE "ENSEIGNANT" 
   (	"MATRICULE" VARCHAR2(4 BYTE), 
	"TITULAIRE" VARCHAR2(4 BYTE), 
	"REMPLACANT" VARCHAR2(4 BYTE), 
	"NOM" VARCHAR2(50 BYTE), 
	"PRENOM" VARCHAR2(50 BYTE), 
	"MAIL" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Index I_FK_ATTRIBUTION_CLA
--------------------------------------------------------

  CREATE INDEX "I_FK_ATTRIBUTION_CLA" ON "ATTRIBUTION" ("SIGLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index I_FK_ENSEIGNANT_CLAS
--------------------------------------------------------

  CREATE INDEX "I_FK_ENSEIGNANT_CLAS" ON "ENSEIGNANT" ("TITULAIRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index I_FK_ENSEIGNANT_CLA1
--------------------------------------------------------

  CREATE INDEX "I_FK_ENSEIGNANT_CLA1" ON "ENSEIGNANT" ("REMPLACANT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Index PK_ATTRIBUTION
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ATTRIBUTION" ON "ATTRIBUTION" ("MATRICULE", "SIGLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Index PK_CLASSE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CLASSE" ON "CLASSE" ("SIGLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Index PK_ENSEIGNANT
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ENSEIGNANT" ON "ENSEIGNANT" ("MATRICULE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Procedure DELETEC
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "DELETEC" (DSIGLE IN CLASSE.SIGLE%TYPE)  
IS  BEGIN  
DELETE FROM CLASSE WHERE DSIGLE=SIGLE;  

END; 

/

--------------------------------------------------------
--  Constraints for Table ATTRIBUTION
--------------------------------------------------------

  ALTER TABLE "ATTRIBUTION" ADD UNIQUE ("MATRICULE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ATTRIBUTION" ADD CONSTRAINT "PK_ATTRIBUTION" PRIMARY KEY ("MATRICULE", "SIGLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ATTRIBUTION" MODIFY ("SIGLE" NOT NULL ENABLE);
  ALTER TABLE "ATTRIBUTION" MODIFY ("MATRICULE" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table CLASSE
--------------------------------------------------------

  ALTER TABLE "CLASSE" ADD CONSTRAINT "PK_CLASSE" PRIMARY KEY ("SIGLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CLASSE" MODIFY ("ORIENTATION" NOT NULL ENABLE);
  ALTER TABLE "CLASSE" MODIFY ("ANNEE" NOT NULL ENABLE);
  ALTER TABLE "CLASSE" MODIFY ("SIGLE" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table ENSEIGNANT
--------------------------------------------------------

  ALTER TABLE "ENSEIGNANT" ADD CONSTRAINT "CH_PARTITION" CHECK ((TITULAIRE IS NULL AND REMPLACANT IS NOT NULL) OR
         (TITULAIRE IS NOT NULL AND REMPLACANT IS NULL) OR
         (TITULAIRE IS NULL AND REMPLACANT IS NULL)) ENABLE;
  ALTER TABLE "ENSEIGNANT" ADD CONSTRAINT "PK_ENSEIGNANT" PRIMARY KEY ("MATRICULE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ENSEIGNANT" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "ENSEIGNANT" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ENSEIGNANT" MODIFY ("MATRICULE" NOT NULL ENABLE);

--------------------------------------------------------
--  Ref Constraints for Table ATTRIBUTION
--------------------------------------------------------

  ALTER TABLE "ATTRIBUTION" ADD CONSTRAINT "FK_ATTR_CLA_SIGLE" FOREIGN KEY ("SIGLE")
	  REFERENCES "CLASSE" ("SIGLE") ENABLE;
  ALTER TABLE "ATTRIBUTION" ADD CONSTRAINT "FK_ATTR_ENSEI_MATR" FOREIGN KEY ("MATRICULE")
	  REFERENCES "ENSEIGNANT" ("MATRICULE") ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table ENSEIGNANT
--------------------------------------------------------

  ALTER TABLE "ENSEIGNANT" ADD CONSTRAINT "FK_ENS_CLA_REMP" FOREIGN KEY ("REMPLACANT")
	  REFERENCES "CLASSE" ("SIGLE") ENABLE;
  ALTER TABLE "ENSEIGNANT" ADD CONSTRAINT "FK_ENS_CLA_TITU" FOREIGN KEY ("TITULAIRE")
	  REFERENCES "CLASSE" ("SIGLE") ENABLE;
