/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projet.Vue.graph.classe;

import Projet.Modele.ClasseModele;
import java.awt.Color;
import java.util.ArrayList;
import Projet.Metier.Classe;
import Projet.Metier.Enseignant;
import java.util.List;

/**
 *
 * @author Guillaume.Rigaux
 */
public class rechClasse extends javax.swing.JPanel {

    private ClasseModele cm;

    public List<Classe> classes;

    public void setModele(ClasseModele cm) {

        this.cm = cm;
    }

    public rechClasse() {
        initComponents();
        this.setBackground(Color.ORANGE);
    }

    public void initPanel() {

        classes = new ArrayList<>(cm.toutesClasses());
        classes = new ArrayList<>(cm.toutesClasses());
        listClasse.removeAllItems();

        classes.forEach((c) -> {

            listClasse.addItem(c);
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        listClasse = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(4, 2));

        jLabel1.setText("Sélectionner la classe parmis la liste");
        add(jLabel1);

        listClasse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listClasseMouseClicked(evt);
            }
        });
        listClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listClasseActionPerformed(evt);
            }
        });
        add(listClasse);

        jButton1.setText("Modifier");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);

        jButton2.setText("Supprimer");
        jButton2.setToolTipText("");
        add(jButton2);
    }// </editor-fold>//GEN-END:initComponents

    private void listClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listClasseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listClasseActionPerformed

    private void listClasseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listClasseMouseClicked
        initPanel();
    }//GEN-LAST:event_listClasseMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Object cla = listClasse.getSelectedItem();
        Classe classe = cm.getClasse((Classe) cla);

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<Classe> listClasse;
    // End of variables declaration//GEN-END:variables
}
