/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projet.Vue.graph;

import Projet.Metier.Attribution;
import Projet.Metier.Classe;
import Projet.Metier.Enseignant;
import java.util.*;
import Projet.Modele.ClasseModele;
import java.awt.Color;
import java.util.function.Consumer;
import javax.swing.JOptionPane;

/**
 *
 * @author Guillaume.Rigaux
 */
public class affichage extends javax.swing.JPanel {

    public List<Enseignant> enseignants;
    public List<Classe> classes;
    public List<Attribution> attributions;

    /**
     * Creates new form affichage
     */
    private ClasseModele cm;

    public void setModele(ClasseModele cm) {

        this.cm = cm;
    }

    public affichage() {

        initComponents();
        this.setBackground(Color.ORANGE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        listeEns = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        listClasses = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        ListAtt = new javax.swing.JComboBox<>();

        jScrollPane1.setViewportView(jEditorPane1);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        jLabel3.setText("jLabel3");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setLayout(new java.awt.GridLayout(6, 2, 5, 5));

        jLabel1.setText("Affichage des enseignants : ");
        add(jLabel1);

        listeEns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeEnsActionPerformed(evt);
            }
        });
        add(listeEns);

        jLabel2.setText("Affichage des classes : ");
        add(jLabel2);

        listClasses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listClassesActionPerformed(evt);
            }
        });
        add(listClasses);

        jLabel4.setText("Affichage des attributions :");
        add(jLabel4);

        ListAtt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(ListAtt);
    }// </editor-fold>//GEN-END:initComponents

    private void listeEnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeEnsActionPerformed


    }//GEN-LAST:event_listeEnsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void listClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listClassesActionPerformed

    }//GEN-LAST:event_listClassesActionPerformed
    public void initPanel() {

        classes = new ArrayList<>(cm.toutesClasses());
        enseignants = new ArrayList<>(cm.tousEns());
        attributions = new ArrayList<>(cm.toutesLesAttributions());

        listeEns.removeAllItems();
        listClasses.removeAllItems();
        ListAtt.removeAllItems();

        enseignants.forEach((Enseignant e) -> {
            listeEns.addItem(e.getNom() + " " + e.getPrenom() + " au matricule " + e.getMatricule() + ", l'adresse mail : " + e.getMail() + " titulaire : " + e.getTitulaire() + " remplacant : " + e.getRemplacant());
        });

        /* for (Classe c : classes){
            listClasses.addItem("Classe :  " + c.getSigle() + " de " + c.getAnnee() + "ème/ère année " + " et d'orientation " + c.getOrientation());
        };
         */
        classes.forEach((c) -> {
            listClasses.addItem("Classe :  " + c.getSigle() + " de " + c.getAnnee() + "ème/ère année " + " et d'orientation " + c.getOrientation());
        });
        attributions.forEach((a) -> {
            ListAtt.addItem(" Sigle de la classe : " + a.getClasse().getSigle() + " | Matricule de la classe : " + a.getEnseignant().getMatricule());
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ListAtt;
    private javax.swing.JButton jButton1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<String> listClasses;
    private javax.swing.JComboBox<String> listeEns;
    // End of variables declaration//GEN-END:variables
}
