/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projet.Vue.graph;

import java.awt.Color;
import javax.swing.JOptionPane;
import Projet.Modele.*;
import Projet.Metier.*;
import java.awt.HeadlessException;

/**
 *
 * @author Guillaume.Rigaux
 */
public class ajoutEnseignant extends javax.swing.JPanel {

    private ClasseModele cm;

    /**
     * Setter du modèle
     * @param cm le modèle à set
     */
    public void setModele(ClasseModele cm) {

        this.cm = cm;
    }

    /**
     * Creates new form ajoutEnseignant
     */
    public ajoutEnseignant() {

        initComponents();
        Color font = new Color(247, 223, 154);
        Color b = new Color(147, 216, 136);
        Color a = new Color(247, 104, 104);
        this.setBackground(font);
        valider.setBackground(b);
        annuler.setBackground(a);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomEns = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        prenomEns = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mailEns = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        matEns = new javax.swing.JTextField();
        valider = new javax.swing.JButton();
        annuler = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(5, 2, 7, 3));

        jLabel1.setText("Entrez le nom de l'enseignant : ");
        add(jLabel1);
        add(nomEns);

        jLabel2.setText("Entrez le prénom de l'enseignant : ");
        add(jLabel2);
        add(prenomEns);

        jLabel3.setText("Entrez l'adresse email : ");
        add(jLabel3);

        mailEns.setFont(new java.awt.Font("sansserif", 2, 12)); // NOI18N
        mailEns.setText("exemple@domaine.com");
        add(mailEns);

        jLabel4.setText("Entrez le matricule de l'enseignant :");
        add(jLabel4);
        add(matEns);

        valider.setText("Valider");
        valider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                validerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                validerMouseExited(evt);
            }
        });
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed(evt);
            }
        });
        add(valider);

        annuler.setText("Annuler");
        annuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                annulerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                annulerMouseExited(evt);
            }
        });
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });
        add(annuler);
    }// </editor-fold>//GEN-END:initComponents

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        nomEns.setText("");
        prenomEns.setText("");
        mailEns.setText("");
        matEns.setText("");
        nomEns.setBackground(Color.white);
        prenomEns.setBackground(Color.white);
        mailEns.setBackground(Color.white);
        matEns.setBackground(Color.white);
    }//GEN-LAST:event_annulerActionPerformed

    private void validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerActionPerformed
        nomEns.setBackground(Color.white);
        prenomEns.setBackground(Color.white);
        mailEns.setBackground(Color.white);
        matEns.setBackground(Color.white);

        boolean erreur = false;
        boolean erreurmail = false;
        boolean erreurmat = false;
        String nom = nomEns.getText();
        if (nom.trim().equals("")) {
            erreur = true;
            nomEns.setBackground(Color.red);
        }
        String prenom = prenomEns.getText();
        if (prenom.trim().equals("")) {
            erreur = true;
            prenomEns.setBackground(Color.red);
        }
        String mail = mailEns.getText();
        if (mail.trim().equals("")) {
            erreur = true;
            mailEns.setBackground(Color.red);
        } else if (!mail.matches("^[A-Za-z0-9]+@[A-Za-z0-9]+\\.[A-Za-z]{2,3}$")) {
            erreurmail = true;
            mailEns.setBackground(Color.red);
        }
        String mat = matEns.getText().toUpperCase();
        if (mat.trim().equals("")) {
            erreur = true;
            matEns.setBackground(Color.red);

        }
        if (mat.length() > 4) {
            erreurmat = true;
            matEns.setBackground(Color.red);
            matEns.setText("Le matricule doit faire 4 caractères !");
        }

        if (!erreur && !erreurmail) {
            try {
                Enseignant e = new Enseignant(mat, nom, prenom, mail);
                //JOptionPane.showMessageDialog(this, e);
                String msg = cm.ajouterEnseignant(e);

                JOptionPane.showMessageDialog(this, msg, "Résultat", JOptionPane.INFORMATION_MESSAGE);

            } catch (HeadlessException e) {
                JOptionPane.showMessageDialog(this, "Erreur d'ajout", "Erreur", JOptionPane.ERROR_MESSAGE);

            }
        } else {
            if (erreur) {
                JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
            if (erreurmail) {
                JOptionPane.showMessageDialog(this, "L'adresse mail doit être au format text@domaine.com", "Erreur du mail", JOptionPane.INFORMATION_MESSAGE);
            }

        }


    }//GEN-LAST:event_validerActionPerformed

    private void validerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validerMouseEntered
        Color b = new Color(138, 254, 71);
        valider.setBackground(b);
    }//GEN-LAST:event_validerMouseEntered

    private void validerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validerMouseExited
        Color b = new Color(147, 216, 136);
        valider.setBackground(b);
    }//GEN-LAST:event_validerMouseExited

    private void annulerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_annulerMouseExited
        Color a = new Color(247, 104, 104);
        annuler.setBackground(a);

    }//GEN-LAST:event_annulerMouseExited

    private void annulerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_annulerMouseEntered
        Color a = new Color(243, 49, 49);
        annuler.setBackground(a);


    }//GEN-LAST:event_annulerMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annuler;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField mailEns;
    private javax.swing.JTextField matEns;
    private javax.swing.JTextField nomEns;
    private javax.swing.JTextField prenomEns;
    private javax.swing.JButton valider;
    // End of variables declaration//GEN-END:variables
}
