/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projet.Vue.graph;

import Projet.Modele.*;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;


import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Guillaume.Rigaux
 */
public class FenetrePrincipale extends javax.swing.JFrame {

    /**
     * Creates new form FenetrePrincipale
     */
    public FenetrePrincipale() {
        initComponents();
        this.setBackground(Color.ORANGE);
        ClasseModele cm = ClasseModeleJDBC.getInstance();
        ajoutEnseignant1.setModele(cm);
        ajoutClasse1.setModele(cm);
        affichage3.setModele(cm);
        affichage3.initPanel();
        rechEnseignant1.setModele(cm);
        rechEnseignant1.initPanel();
        rechClasse3.setModele(cm);
        rechClasse3.initPanel();
        ajoutAttrib2.setModele(cm);
        ajoutAttrib2.initPanel();
        rechAttrib5.setModele(cm);
        rechAttrib5.initPanel();
        
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projet Java");
     

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        affichage1 = new Projet.Vue.graph.affichage();
        affichage2 = new Projet.Vue.graph.affichage();
        ajoutAttrib1 = new Projet.Vue.graph.attribution.ajoutAttrib();
        rechAttrib1 = new Projet.Vue.graph.attribution.rechAttrib();
        rechAttrib2 = new Projet.Vue.graph.attribution.rechAttrib();
        rechAttrib3 = new Projet.Vue.graph.attribution.rechAttrib();
        rechAttrib4 = new Projet.Vue.graph.attribution.rechAttrib();
        ajoutAttrib3 = new Projet.Vue.graph.attribution.ajoutAttrib();
        ajoutAttrib4 = new Projet.Vue.graph.attribution.ajoutAttrib();
        accueil = new javax.swing.JPanel();
        panelAccueil1 = new Projet.Vue.graph.panelAccueil();
        jLabel2 = new javax.swing.JLabel();
        boutonentrer = new javax.swing.JButton();
        ajoutEnseignant1 = new Projet.Vue.graph.enseignant.ajoutEnseignant();
        ajoutClasse1 = new Projet.Vue.graph.classe.ajoutClasse();
        affichage3 = new Projet.Vue.graph.affichage();
        rechEnseignant1 = new Projet.Vue.graph.enseignant.rechEnseignant();
        rechClasse3 = new Projet.Vue.graph.classe.rechClasse();
        ajoutAttrib2 = new Projet.Vue.graph.attribution.ajoutAttrib();
        rechAttrib5 = new Projet.Vue.graph.attribution.rechAttrib();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuEnseignant = new javax.swing.JMenu();
        ajoutEnseignant = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        MenuClasse = new javax.swing.JMenu();
        ajoutclasse = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        MenuAttributions = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        affichage = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        javax.swing.GroupLayout rechAttrib1Layout = new javax.swing.GroupLayout(rechAttrib1);
        rechAttrib1.setLayout(rechAttrib1Layout);
        rechAttrib1Layout.setHorizontalGroup(
            rechAttrib1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        rechAttrib1Layout.setVerticalGroup(
            rechAttrib1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout rechAttrib2Layout = new javax.swing.GroupLayout(rechAttrib2);
        rechAttrib2.setLayout(rechAttrib2Layout);
        rechAttrib2Layout.setHorizontalGroup(
            rechAttrib2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        rechAttrib2Layout.setVerticalGroup(
            rechAttrib2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 102));
        getContentPane().setLayout(new java.awt.CardLayout());

        accueil.setLayout(new java.awt.GridLayout(4, 2, 5, 0));
        accueil.add(panelAccueil1);

        jLabel2.setText("                       Bienvenue sur la page d'accueil du gestionnaire ");
        jLabel2.setMaximumSize(new java.awt.Dimension(15, 16));
        accueil.add(jLabel2);

        boutonentrer.setText("Accéder au gestionnaire");
        boutonentrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonentrerActionPerformed(evt);
            }
        });
        accueil.add(boutonentrer);

        getContentPane().add(accueil, "card4");
        getContentPane().add(ajoutEnseignant1, "card2");
        getContentPane().add(ajoutClasse1, "card3");
        getContentPane().add(affichage3, "card5");
        getContentPane().add(rechEnseignant1, "card6");
        getContentPane().add(rechClasse3, "card7");
        getContentPane().add(ajoutAttrib2, "card8");
        getContentPane().add(rechAttrib5, "card9");

        MenuEnseignant.setText(" Enseignants");

        ajoutEnseignant.setIcon(new javax.swing.ImageIcon("C:\\Users\\guill\\Pictures\\icone.png")); // NOI18N
        ajoutEnseignant.setText("Ajout");
        ajoutEnseignant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutEnseignantActionPerformed(evt);
            }
        });
        MenuEnseignant.add(ajoutEnseignant);

        jMenuItem2.setIcon(new javax.swing.ImageIcon("C:\\Users\\guill\\Pictures\\icone2.png")); // NOI18N
        jMenuItem2.setText("Recherche");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MenuEnseignant.add(jMenuItem2);

        jMenuBar1.add(MenuEnseignant);

        MenuClasse.setText(" Classes");

        ajoutclasse.setIcon(new javax.swing.ImageIcon("C:\\Users\\guill\\Pictures\\icone3.png")); // NOI18N
        ajoutclasse.setText("Ajout");
        ajoutclasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutclasseActionPerformed(evt);
            }
        });
        MenuClasse.add(ajoutclasse);

        jMenuItem5.setIcon(new javax.swing.ImageIcon("C:\\Users\\guill\\Pictures\\icone2.png")); // NOI18N
        jMenuItem5.setText("Recherche");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        MenuClasse.add(jMenuItem5);

        jMenuBar1.add(MenuClasse);

        MenuAttributions.setText("Attributions");

        jMenuItem7.setIcon(new javax.swing.ImageIcon("C:\\Users\\guill\\Pictures\\icone4.png")); // NOI18N
        jMenuItem7.setText("Ajout");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        MenuAttributions.add(jMenuItem7);

        jMenuItem3.setIcon(new javax.swing.ImageIcon("C:\\Users\\guill\\Pictures\\icone2.png")); // NOI18N
        jMenuItem3.setText("Recherche");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        MenuAttributions.add(jMenuItem3);

        jMenuBar1.add(MenuAttributions);

        affichage.setText("Affichages");

        jMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\Users\\guill\\Pictures\\icone5.png")); // NOI18N
        jMenuItem1.setText("Affichage des listes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        affichage.add(jMenuItem1);

        jMenuBar1.add(affichage);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajoutclasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutclasseActionPerformed
        CardLayout cardLayout = (CardLayout) getContentPane().getLayout();
        cardLayout.show(this.getContentPane(), "card3");
    }//GEN-LAST:event_ajoutclasseActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        CardLayout cardLayout = (CardLayout) getContentPane().getLayout();
        cardLayout.show(this.getContentPane(), "card7");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void boutonentrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonentrerActionPerformed
        CardLayout cardLayout = (CardLayout) getContentPane().getLayout();
        cardLayout.show(this.getContentPane(), "card2");
        JOptionPane.showMessageDialog(this, "Bienvenue", "Résultat", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_boutonentrerActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        CardLayout cardLayout = (CardLayout) getContentPane().getLayout();
        cardLayout.show(this.getContentPane(), "card6");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CardLayout cardLayout = (CardLayout) getContentPane().getLayout();
        cardLayout.show(this.getContentPane(), "card5");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        CardLayout cardLayout = (CardLayout) getContentPane().getLayout();
        cardLayout.show(this.getContentPane(), "card8");
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        CardLayout cardLayout = (CardLayout) getContentPane().getLayout();
        cardLayout.show(this.getContentPane(), "card9");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void ajoutEnseignantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutEnseignantActionPerformed
        CardLayout cardLayout = (CardLayout) getContentPane().getLayout();
        cardLayout.show(this.getContentPane(), "card2");
    }//GEN-LAST:event_ajoutEnseignantActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FenetrePrincipale().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAttributions;
    private javax.swing.JMenu MenuClasse;
    private javax.swing.JMenu MenuEnseignant;
    private javax.swing.JPanel accueil;
    private javax.swing.JMenu affichage;
    private Projet.Vue.graph.affichage affichage1;
    private Projet.Vue.graph.affichage affichage2;
    private Projet.Vue.graph.affichage affichage3;
    private Projet.Vue.graph.attribution.ajoutAttrib ajoutAttrib1;
    private Projet.Vue.graph.attribution.ajoutAttrib ajoutAttrib2;
    private Projet.Vue.graph.attribution.ajoutAttrib ajoutAttrib3;
    private Projet.Vue.graph.attribution.ajoutAttrib ajoutAttrib4;
    private Projet.Vue.graph.classe.ajoutClasse ajoutClasse1;
    private javax.swing.JMenuItem ajoutEnseignant;
    private Projet.Vue.graph.enseignant.ajoutEnseignant ajoutEnseignant1;
    private javax.swing.JMenuItem ajoutclasse;
    private javax.swing.JButton boutonentrer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private Projet.Vue.graph.panelAccueil panelAccueil1;
    private Projet.Vue.graph.attribution.rechAttrib rechAttrib1;
    private Projet.Vue.graph.attribution.rechAttrib rechAttrib2;
    private Projet.Vue.graph.attribution.rechAttrib rechAttrib3;
    private Projet.Vue.graph.attribution.rechAttrib rechAttrib4;
    private Projet.Vue.graph.attribution.rechAttrib rechAttrib5;
    private Projet.Vue.graph.classe.rechClasse rechClasse3;
    private Projet.Vue.graph.enseignant.rechEnseignant rechEnseignant1;
    // End of variables declaration//GEN-END:variables
}
