/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projet.Vue.graph;

/**
 *
 * @author Guillaume.Rigaux
 */
public class PanelEnseignant extends javax.swing.JPanel {

    /**
     * Creates new form PanelEnseignant
     */
    public PanelEnseignant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jColorChooser1 = new javax.swing.JColorChooser();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomEnseignant = new javax.swing.JTextField();
        prenomEns = new javax.swing.JTextField();
        matEns = new javax.swing.JTextField();
        boutonValider = new javax.swing.JButton();
        boutonAnnuler = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jFormattedTextField1.setText("jFormattedTextField1");

        jToolBar1.setRollover(true);

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Entrez le nom de l'enseignant : ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 65, -1, -1));

        jLabel2.setText("Entrez le prénom de l'enseignant : ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 109, -1, -1));

        jLabel3.setText("Entrez le matricule de l'enseignant : ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 153, -1, -1));

        nomEnseignant.setText("jTextField1");
        nomEnseignant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomEnseignantActionPerformed(evt);
            }
        });
        add(nomEnseignant, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 59, 190, -1));

        prenomEns.setText("jTextField1");
        prenomEns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomEnsActionPerformed(evt);
            }
        });
        add(prenomEns, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 103, 190, -1));

        matEns.setText("jTextField1");
        matEns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matEnsActionPerformed(evt);
            }
        });
        add(matEns, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 147, 190, -1));

        boutonValider.setText("Valider");
        boutonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonValiderActionPerformed(evt);
            }
        });
        add(boutonValider, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 220, -1, -1));

        boutonAnnuler.setText("Annuler");
        boutonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAnnulerActionPerformed(evt);
            }
        });
        add(boutonAnnuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 220, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void nomEnseignantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomEnseignantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomEnseignantActionPerformed

    private void prenomEnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomEnsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenomEnsActionPerformed

    private void matEnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matEnsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matEnsActionPerformed

    private void boutonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAnnulerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonAnnulerActionPerformed

    private void boutonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonValiderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonValiderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonAnnuler;
    private javax.swing.JButton boutonValider;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField matEns;
    private javax.swing.JTextField nomEnseignant;
    private javax.swing.JTextField prenomEns;
    // End of variables declaration//GEN-END:variables
}
