/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projet.Vue.graph.attribution;

import Projet.Metier.Classe;
import Projet.Metier.Enseignant;
import Projet.Metier.Attribution;
import Projet.Modele.ClasseModele;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Guillaume.Rigaux
 */
public class ajoutAttrib extends javax.swing.JPanel {

    public List<Enseignant> enseignants;
    public List<Classe> classes;
    public List<Attribution> attributions;

    private ClasseModele cm;

    public void setModele(ClasseModele cm) {

        this.cm = cm;
    }

    public ajoutAttrib() {
        initComponents();
        this.setBackground(Color.ORANGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        listEns = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        listClasse = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setLayout(new java.awt.GridLayout(5, 5, 4, 33));

        jLabel2.setText("Liste des enseignants");
        add(jLabel2);

        listEns.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(listEns);

        jLabel3.setText("Liste des classes");
        add(jLabel3);

        listClasse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(listClasse);

        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);

        jButton2.setText("Annuler");
        add(jButton2);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    public void initPanel() {

        classes = new ArrayList<>(cm.toutesClasses());
        enseignants = new ArrayList<>(cm.tousEns());
        attributions = new ArrayList<>(cm.toutesLesAttributions());

        listEns.removeAllItems();
        listClasse.removeAllItems();

        enseignants.forEach((Enseignant e) -> {
            if (e.getTitulaire() == null) {
                listEns.addItem(e.getNom() + " " + e.getPrenom() + " au matricule " + e.getMatricule() + ", l'adresse mail : " + e.getMail() + " titulaire : " + e.getTitulaire() + " remplacant : " + e.getRemplacant());
            }
        });

        classes.forEach((c) -> {

            listClasse.addItem("Classe :  " + c.getSigle() + " de " + c.getAnnee() + "ème/ère année " + " et d'orientation " + c.getOrientation());

        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> listClasse;
    private javax.swing.JComboBox<String> listEns;
    // End of variables declaration//GEN-END:variables
}
