/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projet.Vue.graph.attribution;

import Projet.Metier.Attribution;
import Projet.Metier.Classe;
import Projet.Metier.Enseignant;
import Projet.Modele.ClasseModele;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Guillaume.Rigaux
 */
public class rechAttrib extends javax.swing.JPanel {

    /**
     * Creates new form rechAttrib
     */
    public List<Attribution> attributions;
    
    private ClasseModele cm; 
    
    public void setModele(ClasseModele cm) {

        this.cm = cm;
    }

    public rechAttrib() {
        initComponents();
        this.setBackground(Color.ORANGE);
    }

    public void initPanel() {

       attributions = new ArrayList<>(cm.toutesLesAttributions());

        listAtt.removeAllItems();

        attributions.forEach((a) -> {
            listAtt.addItem(" Sigle de la classe : " + a.getClasse().getSigle() + " | Matricule de la classe : " + a.getEnseignant().getMatricule());
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        listAtt = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(4, 2));

        jLabel1.setText("Sélectionner l'attribution parmis la liste");
        add(jLabel1);

        listAtt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listAtt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listAttMouseClicked(evt);
            }
        });
        listAtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listAttActionPerformed(evt);
            }
        });
        add(listAtt);

        jButton1.setText("Modifier");
        add(jButton1);

        jButton2.setText("Supprimer");
        add(jButton2);
    }// </editor-fold>//GEN-END:initComponents

    private void listAttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listAttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listAttActionPerformed

    private void listAttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listAttMouseClicked
        initPanel();
    }//GEN-LAST:event_listAttMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> listAtt;
    // End of variables declaration//GEN-END:variables
}
