/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projet.Vue.graph.enseignant;

/**
 *
 * @author Guillaume.Rigaux
 */
public class ajoutEnseignantFrame extends javax.swing.JFrame {

    /**
     * Creates new form ajoutEnseignantFrame
     */
    public ajoutEnseignantFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ajoutEnseignant1 = new Projet.Vue.graph.enseignant.ajoutEnseignant();
        jPanel1 = new javax.swing.JPanel();
        ajoutEnseignant2 = new Projet.Vue.graph.enseignant.ajoutEnseignant();
        ajoutEnseignant3 = new Projet.Vue.graph.enseignant.ajoutEnseignant();
        ajoutEnseignant7 = new Projet.Vue.graph.enseignant.ajoutEnseignant();
        ajoutEnseignant4 = new Projet.Vue.graph.enseignant.ajoutEnseignant();
        ajoutEnseignant5 = new Projet.Vue.graph.enseignant.ajoutEnseignant();
        ajoutEnseignant6 = new Projet.Vue.graph.enseignant.ajoutEnseignant();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        javax.swing.GroupLayout ajoutEnseignant1Layout = new javax.swing.GroupLayout(ajoutEnseignant1);
        ajoutEnseignant1.setLayout(ajoutEnseignant1Layout);
        ajoutEnseignant1Layout.setHorizontalGroup(
            ajoutEnseignant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        ajoutEnseignant1Layout.setVerticalGroup(
            ajoutEnseignant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout ajoutEnseignant2Layout = new javax.swing.GroupLayout(ajoutEnseignant2);
        ajoutEnseignant2.setLayout(ajoutEnseignant2Layout);
        ajoutEnseignant2Layout.setHorizontalGroup(
            ajoutEnseignant2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ajoutEnseignant2Layout.setVerticalGroup(
            ajoutEnseignant2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ajoutEnseignant3Layout = new javax.swing.GroupLayout(ajoutEnseignant3);
        ajoutEnseignant3.setLayout(ajoutEnseignant3Layout);
        ajoutEnseignant3Layout.setHorizontalGroup(
            ajoutEnseignant3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajoutEnseignant3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ajoutEnseignant7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ajoutEnseignant3Layout.setVerticalGroup(
            ajoutEnseignant3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajoutEnseignant3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ajoutEnseignant7, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ajoutEnseignant4Layout = new javax.swing.GroupLayout(ajoutEnseignant4);
        ajoutEnseignant4.setLayout(ajoutEnseignant4Layout);
        ajoutEnseignant4Layout.setHorizontalGroup(
            ajoutEnseignant4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ajoutEnseignant4Layout.setVerticalGroup(
            ajoutEnseignant4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ajoutEnseignant5Layout = new javax.swing.GroupLayout(ajoutEnseignant5);
        ajoutEnseignant5.setLayout(ajoutEnseignant5Layout);
        ajoutEnseignant5Layout.setHorizontalGroup(
            ajoutEnseignant5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ajoutEnseignant5Layout.setVerticalGroup(
            ajoutEnseignant5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ajoutEnseignant6Layout = new javax.swing.GroupLayout(ajoutEnseignant6);
        ajoutEnseignant6.setLayout(ajoutEnseignant6Layout);
        ajoutEnseignant6Layout.setHorizontalGroup(
            ajoutEnseignant6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ajoutEnseignant6Layout.setVerticalGroup(
            ajoutEnseignant6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ajoutEnseignant3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ajoutEnseignant3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajoutEnseignantFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajoutEnseignantFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajoutEnseignantFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajoutEnseignantFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ajoutEnseignantFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Projet.Vue.graph.enseignant.ajoutEnseignant ajoutEnseignant1;
    private Projet.Vue.graph.enseignant.ajoutEnseignant ajoutEnseignant2;
    private Projet.Vue.graph.enseignant.ajoutEnseignant ajoutEnseignant3;
    private Projet.Vue.graph.enseignant.ajoutEnseignant ajoutEnseignant4;
    private Projet.Vue.graph.enseignant.ajoutEnseignant ajoutEnseignant5;
    private Projet.Vue.graph.enseignant.ajoutEnseignant ajoutEnseignant6;
    private Projet.Vue.graph.enseignant.ajoutEnseignant ajoutEnseignant7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
