/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projet.Vue.graph.enseignant;

import java.awt.Color;
import javax.swing.JOptionPane;
import Projet.Modele.*;
import Projet.Metier.*;

/**
 *
 * @author Guillaume.Rigaux
 */
public class ajoutEnseignant extends javax.swing.JPanel {

    private ClasseModele cm;

    public void setModele(ClasseModele cm) {

        this.cm = cm;
    }

    /**
     * Creates new form ajoutEnseignant
     */
    public ajoutEnseignant() {
        initComponents();
        this.setBackground(Color.ORANGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomEns = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        prenomEns = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mailEns = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        matEns = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(6, 5, 7, 8));

        jLabel1.setText("Entrez le nom de l'enseignant : ");
        add(jLabel1);
        add(nomEns);

        jLabel2.setText("Entrez le prénom de l'enseignant : ");
        add(jLabel2);
        add(prenomEns);

        jLabel3.setText("Entrez l'adresse email : ");
        add(jLabel3);
        add(mailEns);

        jLabel4.setText("Entrez le matricule de l'enseignant :");
        add(jLabel4);
        add(matEns);

        jButton1.setText("Valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);

        jButton2.setText("Annuler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        nomEns.setText("");
        prenomEns.setText("");
        mailEns.setText("");
        matEns.setText("");
        nomEns.setBackground(Color.white);
        prenomEns.setBackground(Color.white);
        mailEns.setBackground(Color.white);
        matEns.setBackground(Color.white);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        nomEns.setBackground(Color.white);
        prenomEns.setBackground(Color.white);
        mailEns.setBackground(Color.white);
        matEns.setBackground(Color.white);

        boolean erreur = false;
        boolean erreurmail = false; 
        String nom = nomEns.getText();
        if (nom.trim().equals("")) {
            erreur = true;
            nomEns.setBackground(Color.red);
        }
        String prenom = prenomEns.getText();
        if (prenom.trim().equals("")) {
            erreur = true;
            prenomEns.setBackground(Color.red);
        }
        String mail = mailEns.getText();
        if (mail.trim().equals("")) {
            erreur = true;
            mailEns.setBackground(Color.red);
        } else if (!mail.matches("^[A-Za-z0-9]+@[A-Za-z0-9]+\\.[A-Za-z]{2,3}$")) {
            erreurmail = true;
            mailEns.setBackground(Color.red);
        }
        String mat = matEns.getText().toUpperCase();
        if (mat.trim().equals("")) {
            erreur = true;
            matEns.setBackground(Color.red);
        }

        if (!erreur && !erreurmail) {
            Enseignant e = new Enseignant(mat, nom, prenom, mail);
            //JOptionPane.showMessageDialog(this, e);
            String msg = cm.ajouterEnseignant(e);
            JOptionPane.showMessageDialog(this, msg, "Résultat", JOptionPane.INFORMATION_MESSAGE);
        } 
         else {
            if(erreur) JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs", "Erreur", JOptionPane.ERROR_MESSAGE);
            if(erreurmail) JOptionPane.showMessageDialog(this, "L'adresse mail doit être au format text@domaine.com", "Erreur du mail", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField mailEns;
    private javax.swing.JTextField matEns;
    private javax.swing.JTextField nomEns;
    private javax.swing.JTextField prenomEns;
    // End of variables declaration//GEN-END:variables
}
