/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projet.Vue.graph.enseignant;

import java.awt.Color;
import javax.swing.JOptionPane;
import Projet.Modele.*;
import Projet.Metier.*;

/**
 *
 * @author Guillaume.Rigaux
 */
public class AjoutEnseignant extends javax.swing.JPanel {

    private ClasseModele cm;

    /**
     * Creates new form ajoutEnseignant
     */
    public AjoutEnseignant() {
        initComponents();
    }

    public void setModele(ClasseModele cm) {

        this.cm = cm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomEns = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        prenomEns = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mailEns = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        matEns = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(5, 2, 6, 6));

        jLabel1.setText("Nom de l'enseignant : ");
        add(jLabel1);

        nomEns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomEnsActionPerformed(evt);
            }
        });
        add(nomEns);

        jLabel2.setText("Prénom de l'enseignant : ");
        add(jLabel2);
        add(prenomEns);

        jLabel3.setText("Email de l'enseignant : ");
        add(jLabel3);
        add(mailEns);

        jLabel4.setText("Matricule de l'enseignant : ");
        add(jLabel4);

        matEns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matEnsActionPerformed(evt);
            }
        });
        add(matEns);

        jButton1.setText("Valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);

        jButton2.setText("Annuler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        nomEns.setBackground(Color.white);
        prenomEns.setBackground(Color.white);
        mailEns.setBackground(Color.white);
        matEns.setBackground(Color.white);

        boolean erreur = false;
        String nom = nomEns.getText();
        if (nom.trim().equals("")) {
            erreur = true;
            nomEns.setBackground(Color.red);
        }
        String prenom = prenomEns.getText();
        if (prenom.trim().equals("")) {
            erreur = true;
            prenomEns.setBackground(Color.red);
        }
        String mail = mailEns.getText();
        if (mail.trim().equals("")) {
            erreur = true;
            mailEns.setBackground(Color.red);
        }
        String mat = matEns.getText();
        if (mat.trim().equals("")) {
            erreur = true;
            matEns.setBackground(Color.red);
        }

        if (!erreur) {
            Enseignant e = new Enseignant(mat, nom, prenom, mail);
            //JOptionPane.showMessageDialog(this, e);
            String msg = cm.ajouterEnseignant(e);
            JOptionPane.showMessageDialog(this, msg, "Résultat", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this,"Veuillez remplir tous les champs", "Erreur", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void matEnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matEnsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matEnsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        nomEns.setText("");
        prenomEns.setText("");
        mailEns.setText("");
        matEns.setText("");
        nomEns.setBackground(Color.white);
        prenomEns.setBackground(Color.white);
        mailEns.setBackground(Color.white);
        matEns.setBackground(Color.white);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void nomEnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomEnsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomEnsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField mailEns;
    private javax.swing.JTextField matEns;
    private javax.swing.JTextField nomEns;
    private javax.swing.JTextField prenomEns;
    // End of variables declaration//GEN-END:variables
}
